### ISSUE TITLE
How to use with subclass of UINavigationController?

### ISSUE THREAD

**Issue by zenghaojim33** [yiplee/YPNavigationBarTransition#10]
Follow the instruction of `YPNavigationController`, but method `validateInnerNavigationDelegate` and variable `navigationController` does not exist. So what should i do if i want to make a `UINavigatioController` subclass to use in the project?

**Comment by yiplee** [comment]
checkout tag 1.0.4 and then you will see it.

```YPNavigationController``` is removed at last version for the misuse of ```UINavigationControllerDelegate```; I'm working on a new version of YPNavigationController and I will post it here when it's done.

If you already have an UINavigationControllerDelegate implementation,  YPNavigationController is not needed as transition center is powered by the willShow & didShow methods, see [YPNavigationBarTransitionCenter.h](https://github.com/yiplee/YPNavigationBarTransition/blob/master/YPNavigationBarTransition/YPNavigationBarTransitionCenter.h) for details.

**Comment by yiplee** [comment]
New YPNavigationController : https://github.com/yiplee/YPNavigationBarTransition/blob/master/YPNavigationBarTransition-Example/YPNavigationController.m

**Comment by yiplee** [comment]
YP
