### ISSUE TITLE
How to use it in Swift?

### ISSUE THREAD

**Issue by StormXX** [yiplee/YPNavigationBarTransition#12]

**Comment by StormXX** [comment]
我现在导入了这个库，然后也实现了YPNavigationBarConfigureStyle。。。但是并没有起作用。。。因为example里面的也无效。。所以我现在很懵逼。。。

**Comment by StormXX** [comment]
我是用pod导入的

**Comment by yiplee** [comment]
OC 项目吗？需要用 YPNavigationController 代替你的 UINavigationController ，然后还要给 YPNavigationController 实现 YPNavigationBarConfigureStyle。见 https://github.com/yiplee/YPNavigationBarTransition/blob/master/YPNavigationBarTransition-Example/AppDelegate.m#L25 和 https://github.com/yiplee/YPNavigationBarTransition/blob/master/YPNavigationBarTransition-Example/YPNavigationController%2BConfigure.m

**Comment by StormXX** [comment]
Swift项目，你上面的解答应该能解决我的问题，我去试试。 非常感谢您抽出宝贵的时间回答我！

**Comment by yiplee** [comment]
嗯，我今天晚些时候弄一个 swift demo 出来。

**Comment by StormXX** [comment]
现在我遇到一个问题。yp_navigtionBarConfiguration这个返回的configurations是枚举，在OC里面可以用“|”符号来把多个枚举连一起，但是Swift不行。 
UIView.animate这个方法里面的UIViewAnimationOptions也是这样的，但是swift写法可以用数组，比如之前是 curveIn | curveOut, Swift的话就是[.curveIn, .curveOut]。
我刚翻了一下UIViewAnimationOptions这个枚举的实现，它为这个枚举实现了一个叫做 `OptionSet` 的协议，所以才可以那样子。 OC这边我不知道要怎么改。。。因为我好久没写OC了= =
你看你是否有空方便研究一下，或者我今天晚些时候研究一下，如果有方法的话我来issue通知你。
（你的这个库超棒，非常感谢，同时期待你的Swift重写版

**Comment by yiplee** [comment]
感谢提醒。我想用 swift 重写也是想让在 swift 项目上用起来更流畅一点。

有好的方法可以提 PR 给我，共同完善这个库。

**Comment by yiplee** [comment]
我刚发布了 2.0.4 版本，Swift 项目可以正常用 Pod 引入了，记得用 use_frameworks!

Examples 下有个 swift 版本的 demo 可供参考。

**Comment by StormXX** [comment]
@yiplee  好的，谢谢!
