### ISSUE TITLE
pod install 后找不到YPNavigationController

### ISSUE THREAD

**Issue by xiamoon** [yiplee/YPNavigationBarTransition#17]
我的Podfile：
platform :ios, '9.0'
use_frameworks!

target 'TestSingleNavigationBar' do
pod 'YPNavigationBarTransition', '~> 2.0'
end

**Comment by xiamoon** [comment]
我的Podfile：
platform :ios, '9.0'
use_frameworks!

target 'TestSingleNavigationBar' do
    pod 'YPNavigationBarTransition', '~> 2.0'
end

**Comment by yiplee** [comment]
在 Pods/YPNavigationBarTransition 里面能找到 YPNavigationController.{h,m} 吗？
还是说编译不过呢？

**Comment by yiplee** [comment]
另外看一下 Podfile.lock 文件里面 YPNavigationBarTransition 的版本

**Comment by xiamoon** [comment]
1. 在 Pods/YPNavigationBarTransition 里面不能找到 YPNavigationController.{h,m} .
编译没有报错。

 2. Podfile.lock如下：
PODS:
  - YPNavigationBarTransition (2.0.0)
  - YYKit (1.0.9):
    - YYKit/no-arc (= 1.0.9)
  - YYKit/no-arc (1.0.9)

DEPENDENCIES:
  - YPNavigationBarTransition (~> 2.0)
  - YYKit

SPEC CHECKSUMS:
  YPNavigationBarTransition: 848c3c52f05175a084957bce4ddb0140178a5285
  YYKit: 7cda43304a8dc3696c449041e2cb3107b4e236e7

PODFILE CHECKSUM: 5219b6c0e27935cb86e2667533c7c183811e22c9

COCOAPODS: 1.4.0

**Comment by yiplee** [comment]
现在 YPNavigationBarTransition 最新版本是 2.0.4，升级一下

**Comment by xiamoon** [comment]
pod 'YPNavigationBarTransition', '~> 2.0.4' 找不到2.0.4这个版本

**Comment by yiplee** [comment]
```ruby
pod repo update
```

试试先 update 一下 pod repo

**Comment by xiamoon** [comment]
刚按你的方法更新了CocoaPods，更新了蛮久，然后再次pod install试了下可以了。
谢谢你的及时回复，你的库写的非常棒！

**Comment by yiplee** [comment]
👌使用过程中遇到任何问题欢迎通过 Issue 和 PR 给我反馈！

这个 issue 我先关了。
