### ISSUE TITLE
模态跳转后，再返回会有问题

### ISSUE THREAD

**Issue by chunipo** [yiplee/YPNavigationBarTransition#20]

**Comment by yiplee** [comment]
有什么问题呢？

**Comment by chunipo** [comment]
没想到你回复那么快，事情是这样的，
我把视图控制器装在导航控制器上，然后主控制器是tabbarController。
当我点击tabbar下的按钮时，有些界面涉及到登录注册，如果未注册的话，会先跳转到登录注册界面，这个时候，我是把注册界面装在导航控制器里，然后模态跳转跳转过去。
然后在dismiss之后，界面上部分会多出一个黑色的navigationbar
我把操作视频发给你看一下把

**Comment by chunipo** [comment]
[Uploading 归档 3.zip…]()

**Comment by chunipo** [comment]
[归档 3.zip](https://github.com/yiplee/YPNavigationBarTransition/files/2132458/3.zip)

**Comment by yiplee** [comment]
视频我看了。你的登录注册页面是 present 出来的，为啥左上角会有返回呢？
理论上 present 出来的 navigation controller 是一个新的 navigation controller，不会影响下面的 controller。
能提供一个可以复现这个 bug 的 demo 我看看么？

**Comment by chunipo** [comment]
左上角的返回也是模态跳转的，设计图如此；
好的，我给一个demo给你，麻烦你看看，三克油～

**Comment by chunipo** [comment]
不好意思，那么晚回你，我把demo压缩了还挺大的，放到的云盘里，麻烦你看看可以下载吗？
链接: https://pan.baidu.com/s/1fRjv0lKfmYSLxDuvr8gLwQ 密码: cvdw

**Comment by yiplee** [comment]
👌 可以下载
你为啥不新开一个 repo 放在 github 上呢

**Comment by chunipo** [comment]
哎哟，忘记了

**Comment by chunipo** [comment]
忘记提醒你，主函数在main文件夹里，可以从里面追溯到问题文件，点击中间按钮时

**Comment by yiplee** [comment]
已确认是异步判断添加 fake bar 导致的问题
我已经发布了 2.0.6 版本修复了这个 bug
执行 ```pod repo update``` 然后再 ```pod install``` 安装最新版本再试试。

**Comment by chunipo** [comment]
好的，感谢大力帮忙，我去看看

**Comment by chunipo** [comment]
我更新到了最新版本2.0.6，不过发现还是有问题，另外YPNavigationBarHidden这个属性也没有生效了～

**Comment by yiplee** [comment]
稍等 我看下

**Comment by chunipo** [comment]
好的

**Comment by chunipo** [comment]
我试了一下，之前的问题还存在
另外YPNavigationBarHidden跟YPNavigationBarShow的属性被交换了。

**Comment by yiplee** [comment]
你再更新到 2.0.7版本。然后，bar hidden 不起作用，是因为下图的这个，也需要设置下。

![image](https://user-images.githubusercontent.com/1432077/41889718-8f81ffb6-793e-11e8-9879-e2152facb831.png)

**Comment by chunipo** [comment]
好的，我看一下
