### ISSUE TITLE
跳转到继承UITableViewController的界面会出现导航栏跳跃问题

### ISSUE THREAD

**Issue by ETmanwenhan** [yiplee/YPNavigationBarTransition#21]
跳转到继承UITableViewController的界面会出现导航栏跳跃问题，尽管我设置了self.extendedLayoutIncludesOpaqueBars = true，还是会出现跳跃问题。

**Comment by yiplee** [comment]
导航栏跳跃是指？
另外你用的版本是最新的 2.0.7 么？

**Comment by ETmanwenhan** [comment]
2.0.5
使用的是pod

**Comment by ETmanwenhan** [comment]
第一个界面是导航栏渐变，第二个界面是继承UITableViewController
当第一个界面还没出现导航栏时，点击cell跳转到第二个界面，就会产生第二个界面导航栏往上跳的情况。

**Comment by ETmanwenhan** [comment]
CocoaPods安装不了 2.0.7版本哦

[!] CocoaPods could not find compatible versions for pod "YPNavigationBarTransition":
  In Podfile:
    YPNavigationBarTransition (~> 2.0.7)

None of your spec sources contain a spec satisfying the dependency: `YPNavigationBarTransition (~> 2.0.7)`.

**Comment by yiplee** [comment]
感觉这种 UI 上的问题还是得录个视频直观点，我建了一个交流反馈群，方便的话录屏了发在里面我看看。

![img_0241](https://user-images.githubusercontent.com/1432077/41957663-423092cc-7a1a-11e8-8902-2c9efc709e46.jpg)

**Comment by yiplee** [comment]
2.0.7 版本我昨天发布的，得 ```pod repo update``` 一下再 install。

**Comment by ETmanwenhan** [comment]
Demo中我也可以模拟这种情况给你看看。

YPDemoConfigureViewController中修改该方法：
```object
- (void) showNextViewControllerWithColor:(UIColor *)color {
    
    UITableViewController *controller = [[UITableViewController alloc] init];
    controller.hidesBottomBarWhenPushed = YES;
    [self.navigationController pushViewController:controller animated:YES];
}
```

然后启动Demo，点击IMAGES:Yellow->COLORS:Red，你就会看到这个问题了
