### ISSUE TITLE
白色导航栏下面那条横线不能显示吗？

### ISSUE THREAD

**Issue by xiafb** [yiplee/YPNavigationBarTransition#24]
用颜色设置导航栏为白色的时候，下面那条横线不能设置显示

**Comment by yiplee** [comment]
额，怎么关了。

我刚提交了一个 PR ： ShadowImage，加了
![screen shot 2018-08-29 at 3 02 59 pm](https://user-images.githubusercontent.com/1432077/44771109-a8339200-ab9c-11e8-9774-5ccecf289346.png)


你试试这个分支的代码

```ruby
pod 'YPNavigationBarTransition', :git => 'https://github.com/yiplee/YPNavigationBarTransition.git', :branch => 'shadowImage'
```

没问题的话我再发布到 CocoaPods 上面去。

**Comment by yiplee** [comment]
Configure 里面加上 ```YPNavigationBarShowShadowImage``` 即可。

**Comment by xiafb** [comment]
颜色设置放在基类里，现在两个不同颜色的控制器跳转的时候，不同颜色有个很明显的闪现，请教下什么原因

**Comment by yiplee** [comment]
@xiafb 有 demo 可以重现吗？我看看代码。

**Comment by xiafb** [comment]
[Demo.zip](https://github.com/yiplee/YPNavigationBarTransition/files/2334317/Demo.zip)
做了个简单Demo，能重现一下我项目中的问题

**Comment by yiplee** [comment]
我看了下，第一次 push base2ViewController 会这样。最简单的解决方式就是给 base2 加上
```objc
self.extendedLayoutIncludesOpaqueBars = TRUE;
```

在 navigation bar 完全不透明的时候，也让 vc.view 铺满整个屏幕。

**Comment by yiplee** [comment]
我刚更新了下 shadowImage 分支，现在应该不加 extendedLayoutIncludesOpaqueBars 也没这个问题了。
