### ISSUE TITLE
Status bar could not find cached time string image.

### ISSUE THREAD

**Issue by Dale-iOS** [yiplee/YPNavigationBarTransition#26]
控制台一直打印这个？

**Comment by yiplee** [comment]
https://stackoverflow.com/questions/49586341/status-bar-could-not-find-cached-time-string-image-rendering-in-process

**Comment by Dale-iOS** [comment]
并不能解决问题，问题出现在切换不同样式导航栏的时候，控制台会打印这个警告

**Comment by yiplee** [comment]
这个 issue 我先关了。
如果还有问题，可以开新的 issue。
