### ISSUE TITLE
Example for Swift

### ISSUE THREAD

**Issue by sLm-s** [yiplee/YPNavigationBarTransition#29]
Unfortunately I can not figure out how to use your library in Swift. If possible, rewrite the same example on Swift.

**Comment by yiplee** [comment]
![image](https://user-images.githubusercontent.com/1432077/52472113-7ef84280-2bcd-11e9-9419-b9054e2cea5c.png)

**Comment by zaidqattan** [comment]
Hello @yiplee 
thank you for this awesome library,
when I tried to open and read the swift version I found all files are wrriten in Obj-c
is there any problem ? please help
<img width="287" alt="Screen Shot 2020-05-29 at 5 35 20 PM" src="https://user-images.githubusercontent.com/43964601/83271740-ee36e300-a1d2-11ea-949d-ca09aa3ca2b9.png">
