### ISSUE TITLE
如何在Translucent时排除状态栏？

### ISSUE THREAD

**Issue by internalG** [yiplee/YPNavigationBarTransition#30]
- (YPNavigationBarConfigurations) yp_navigtionBarConfiguration {
    return YPNavigationBarBackgroundStyleTranslucent | YPNavigationBarBackgroundStyleColor;
}

- (UIColor *) yp_navigationBarTintColor {
    return [UIColor redColor];
}

- (UIColor *) yp_navigationBackgroundColor {
    return [UIColor whiteColor];
}

目前视图向上滚动时会出现在naviagtionbar和statusbar下面，如何排除statusbar使Translucent效果只出现在naviagtionbar？

**Comment by yiplee** [comment]
能贴一下现在的效果图以及你想要的效果吗？我理解的是你想要  status bar 不透明是吧？

**Comment by internalG** [comment]
对，导航栏透明而状态栏不透明。

**Comment by internalG** [comment]
目前发现YPNavigationBarHidden时，view也会显示到statusbar里面，用示例应用就能重现，希望有选项保持statusbar始终保持原样。

**Comment by yiplee** [comment]
status bar 本来就是透明的，在有导航栏的时候它的底色就是底下导航栏的颜色。你打开 iOS 系统设置就能看到 status bar 下面也有毛玻璃效果。
导航栏 hidden 之后，view 肯定就会显示在 status bar 下面了。
如果你不想让 status bar 下面有透明效果，一是设置导航栏不透明，二是手动设置 status bar 的背景颜色

```swift
var statusBarView = UIApplication.SharedApplication.ValueForKey(new NSString("statusBar")) as UIView;
statusBarView.BackgroundColor = UIColor.Green;
```

但是 status bar 是全局的，所以你要自己维护它的状态。

**Comment by internalG** [comment]
按理说去掉controller的under top bar设置也可以，可是好像不行。另外发现push到UIPageViewController里面时后退手势失效了，可能是什么原因？

**Comment by internalG** [comment]
@implementation YPDemoContainerViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
//    self.extendedLayoutIncludesOpaqueBars = YES;
    self.edgesForExtendedLayout = UIRectEdgeBottom;

改成上面这段代码就无法做到透明了，是不支持edgesForExtendedLayout属性？

**Comment by yiplee** [comment]
```extendedLayoutIncludesOpaqueBars``` 是让 controller 的 view frame top 和 navigation bar 的 top 对齐的；```edgesForExtendedLayout``` 改成 ```UIRectEdgeBottom``` 之后，controller view 的 frame 都变了。

push 到 UIPageViewController 后左滑失效应该是 UIPageViewController 的左右滑手势优先响应了滑动操作，可以看看 ```UIGestureRecognizer``` 的 ```- (void)requireGestureRecognizerToFail:(UIGestureRecognizer *)otherGestureRecognizer```

**Comment by yiplee** [comment]
这个我先关了，还有问题可以新开 issue。
