### ISSUE TITLE
设置 extendedLayoutIncludesOpaqueBars 为 true 还是会引起 tableView 跳动一下

### ISSUE THREAD

**Issue by shengwanlin** [yiplee/YPNavigationBarTransition#40]
A push  B

全局默认设置：
extension YPNavigationController : NavigationBarConfigureStyle {
  public func yp_navigtionBarConfiguration() -> YPNavigationBarConfigurations {
    return [.backgroundStyleColor, .backgroundStyleOpaque]
  }
  
  public func yp_navigationBarTintColor() -> UIColor! {
    return UIColor.white
  }
  
  public func yp_navigationBackgroundColor() -> UIColor! {
    return Specs.color.tint
  }
}

A 设置： （设置 extendedLayoutIncludesOpaqueBars 为 true ）
extension A : NavigationBarConfigureStyle {
  public func yp_navigtionBarConfiguration() -> YPNavigationBarConfigurations {
    return [.backgroundStyleTransparent]
  }
  
  public func yp_navigationBarTintColor() -> UIColor! {
    return UIColor.white
  }
}

B 设置：

extension B : NavigationBarConfigureStyle {
  public func yp_navigtionBarConfiguration() -> YPNavigationBarConfigurations {
    return [.backgroundStyleColor, .backgroundStyleOpaque]
  }
  
  public func yp_navigationBarTintColor() -> UIColor! {
    return UIColor.white
  }
  
  func yp_navigationBackgroundColor() -> UIColor! {
    return UIColor(hex: 0x40362E)
  }
}

**Comment by yiplee** [comment]
你的设置里面，B 的 navigationBar 是不透明的，所以需要把 B 的 extendedLayoutIncludesOpaqueBars 设置为 true

**Comment by shengwanlin** [comment]
@yiplee 多谢，但是这样设置后 tableview 不会自动调整 insets, 内容会被 navigationbar 覆盖

**Comment by yiplee** [comment]
手动设置 insets 即可

**Comment by shengwanlin** [comment]
好
