### ISSUE TITLE
無法返回

### ISSUE THREAD

**Issue by rick205w** [yiplee/YPNavigationBarTransition#45]
demo 上下滑動完後， 有時可以側滑返回，有時又不行，不知是否是bug

**Comment by yiplee** [comment]
最近的一个 pr 改了这个 https://github.com/yiplee/YPNavigationBarTransition/pull/44
你试下回退到这个 pr 之前的 commit 看看有没有问题

**Comment by rick205w** [comment]
好的我再試試 感謝您
