### ISSUE TITLE
模态弹出导航控制器。导航栏没效果

### ISSUE THREAD

**Issue by xiafb** [yiplee/YPNavigationBarTransition#9]
模态弹出导航控制器。导航栏没效果，白色的

**Comment by yiplee** [comment]
建议你 subclass 一个 UINavigationController 并且封装一个 ```YPNavigationBarTransitionCenter``` 在里面，然后实现 UINavigationControllerDelegate。然后 present 的时候都用你自己的导航控制器。

**Comment by xiafb** [comment]
请问有 YPNavigationController 参考一下吗？

**Comment by yiplee** [comment]
@xiafb  [YPNavigationController](https://github.com/yiplee/YPNavigationBarTransition/blob/1.0.4/YPNavigationBarTransition-Example/YPNavigationController.m) 这是 1.0.x 版本我放在 example 里面的，对 delegate 的处理有点问题，后面我删掉了，你可以参考下。

**Comment by yiplee** [comment]
new YPNavigationController :
https://github.com/yiplee/YPNavigationBarTransition/blob/master/YPNavigationBarTransition-Example/YPNavigationController.m
